package com.example.fitappa.Exercise.Exercise;

import com.example.fitappa.Exercise.Set.Settable;

import java.io.Serializable;

public abstract class Exercise implements Serializable {
    protected String name;

    /**
     * Constructor for a User class, takes in all necessary variables needed to make a User
     *
     * @param name   The String name referring to the name of the exercise
     */
    public Exercise(String name) {
        this.name = name;
    }

    // empty constructor necessary for firebase
    @SuppressWarnings("unused")
    public Exercise() {
    }

    /**
     * Creates an Exercise object given another.
     *
     * @param other - the other exercise
     */
    public Exercise(Exercise other) {
        this.name = other.name;
    }


    /**
     * returns the name of the exercise
     *
     * @return the string name
     */
    public String getName() {
        return name;
    }

    /**
     * We define volume to be the total work done in an exercise. The exact computation of volume highly depends
     * on the type of exercise.
     *
     * @return the total volume generated by this exercise.
     */
    public abstract double volume();

    public abstract void addSet(Settable s);

}