package com.example.fitappa.Exercise.Exercise;

import com.example.fitappa.Exercise.Set.Settable;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

public class Exercise<T> implements Serializable {
    protected String name;
    protected List<T> sets;

    /**
     * Constructor for a User class, takes in all necessary variables needed to make a User
     *
     * @param name   The String name referring to the name of the exercise
     */
    public Exercise(String name) {
        this.name = name;
        this.sets = new ArrayList<>();
    }

    // empty constructor necessary for firebase
    @SuppressWarnings("unused")
    public Exercise() {
    }

    /**
     * returns the name of the exercise
     *
     * @return the string name
     */
    public String getName() {
        return name;
    }

    /**
     * We define volume to be the total work done in an exercise. The exact computation of volume highly depends
     * on the type of exercise.
     *
     * @return the total volume generated by this exercise.
     */
    public double volume() {
        double vol = 0;
        for(T s : sets) {
            vol += ((Settable) s).volume();
        }
        return vol;
    }
    /**
     * return the number of sets in the Exercise
     * @return size of this.sets
     */
    public int numSets() {
        return this.sets.size();
    }


    /**
     * A crucial component of an exercise is the ability to add sets
     * However, every exercise is different and has different types of sets.
     * Sometimes the sets are completely unrelated.
     *
     * In this case, we defer the implementation of addSet to the concrete implementations
     * of exercise.
     *
     * @param s represents the set
     */
    public void addSet(T s) {
        this.sets.add(s);
    }

}