package com.example.fitappa.Workout.Core;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/**
 * Represents the Track Workout Use Case.
 *
 * Fundamentally, this class should enable you to track workouts and store
 * them in history.
 *
 * @author abdullah
 * @version 0.1
 */
public class AnalyzeWorkouts implements Serializable {
    private final List<PerformWorkout> performWorkouts;

    /**
     * Creates a workout tracker with an empty history
     */
    public AnalyzeWorkouts() {
        this.performWorkouts = new ArrayList<>();
    }

    /**
     * @return The total volume generated by all the workouts in the tracker.
     */
    public double volume() {
        double vol = 0;
        for(PerformWorkout performWorkout : performWorkouts) {
            vol += performWorkout.volume();
        }
        return vol;
    }

    /**
     * @return The average duration of a workout in the tracker
     */
    public double getAvgDuration() {
        /*double sum = 0;

        for (WorkoutTemplate workoutTemplate : this.workoutTemplateHistory) {
            sum += workoutTemplate.calc().toMinutes();
        }

        return sum / this.workoutTemplateHistory.size();*/
        return 0;
    }

    /**
     * This method return the total workouts that were tracked
     * @return the total workouts that were tracked
     */
    public int getTotalWorkouts() {
        return this.performWorkouts.size();
    }


}
